version: "3.4"

# Development environment override
services:
  php:
    build:
      args:
        APP_ENV: ${APP_ENV:-dev}
        SYMFONY_DECRYPTION_SECRET: ${SYMFONY_DECRYPTION_SECRET}
    volumes:
      # For PHP:
      - ./:/srv/app
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      # If you develop on Mac you can remove the var/ directory from the bind-mount
      # for better performance by enabling the next line
      # - /srv/app/var
      # For Caddy:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      # - ./public:/srv/app/public:ro
    environment:
      APP_ENV: ${APP_ENV:-dev}
      SYMFONY_DECRYPTION_SECRET: ${SYMFONY_DECRYPTION_SECRET}
    depends_on:
      - database
      - redis


###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
        - "3306:3306"

  database-test:
    image: mysql:${MYSQL_VERSION:-8.0}
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: app_test
      MYSQL_PASSWORD: a2iziJggG6ch
      MYSQL_USER: dbusertest
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - db-data-test:/var/lib/mysql:rw
    ports:
      - "3307:3306"
###< doctrine/doctrine-bundle ###

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD:-ChangeMe}

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
###< symfony/mailer ###

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT:-8080}:8080

volumes:
  php_socket:
  caddy_data:
  caddy_config:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
###> doctrine/doctrine-bundle ###
  db-data:
  db-data-test:
###< doctrine/doctrine-bundle ###
